spring:
  application:
    name: ApiGateWay
  cloud:
    gateway:
          routes:
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/order/**
            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/pay/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

